### ISSUE TITLE
[BE][Bug] Obstacle color uses the color of the obstacle edge and not the area.

### ISSUE THREAD

**Issue by Poetzi** [fragjulian/ASE-WS22-MazeRunner#52]
You use the pixelcolor of the border of the obstacles (219,219,219) and not the color of the area (180,180,180) where the user clicks with the color picker. The path doesn't work if you don't use the color of the edge pixels of the obstacles. It just ignores the obstacles instead. You can't expect a user to click pixel perfect on the edge.

**Comment by gregorla12** [comment]
![Image](https://user-images.githubusercontent.com/94615170/209987903-83384287-8f5c-45b5-bc74-1f4b871bd990.png)

Please include more details in your bug report. Which maze are you refering to? What do you mean by border of the obstacles? The obstacles in the examples are only made of one color (219,219,219). They do not have any border in a different color. I manually checked and there are no pixels of the color 180,180,180 in the example mazes. I tried to open the original image in gray scale. Then I used a color picker to pick the rgb value of the obstacle pixles in the gray image. The color of the gray pixels then was 180, 180, 180. We are using the following image type: BufferedImage.TYPE_INT_RGB.  We are not using the gray value, we convert the image to our image type and all colors must be in that color space. I can try to include a conversion of the colorspace you are using but I need more details about how the color picker works and what image type you are refering to. 
For the obstacle avoidance algorithm it does not matter if the edge of an obstacle has the obstacle color or the area. If there is a pixel of the obstacle color the safety distance will be considered. 
Please also make sure that the color picker is only picking colors of single pixels and not the average of multiple pixels. The edge has the same color as all the other pixels.

**Comment by Poetzi** [comment]
Ok i had a look at it again. Our colorpicker doesn't support .tif files. If you convert the .tif maze to jpeg or png it always puts pixels of another color at the edge of the obstacles like a fading edge. I don't know how to resolve this. Perhaps you will have an idea, as I don't know how to resolve this.

**Comment by fragjulian** [comment]
Solved this by allowing only certain file formats.
