### ISSUE TITLE
[BE] improve scalability

### ISSUE THREAD

**Issue by fragjulian** [fragjulian/ASE-WS22-MazeRunner#66]
ideas as discused:

- add timout in case the image is too big or the server is overloaded with requests (incl. proper error codes)
- implement async processing using queues

create separate issues as necessary

**Comment by gregorla12** [comment]
The requests are now processed asynchronously (will be ready for review soon). I am not using any queues. The async processing in Spring boot is done by the AtAsynk annotation, which I decided to use. I do think that this will work better than implementing it by hand. 
Spring also has a timeout for requests including proper error codes. The timeout can be set explicitly by the parameter spring.mvc.async.request-timeout.
I have included additional checks for a maximum image size to avoid running into those timeouts in the first place.
The first image attached shows such an error message before I implemented proper checks for the maximum allowed dimensions. I set the size of the image to something huge (please note that the path design has changed already, I was testing different options). 

![Image](https://user-images.githubusercontent.com/94615170/211162265-ceac2e1c-3380-456b-8319-90718b0f125d.png)
The second image shows the console running into such a timeout.
![Image](https://user-images.githubusercontent.com/94615170/211163392-d09f6fd8-ef08-4606-a955-63a1c42bb157.png)

**Comment by fragjulian** [comment]
Awesome! I did not know about these built-in features :)
