### ISSUE TITLE
[FE][Bug] getSolvedPath in maze-builder.component is called too early on mouseUp event

### ISSUE THREAD

**Issue by florianlan** [fragjulian/ASE-WS22-MazeRunner#77]
When the handleMouseUp event is called, the Endpoint for solving the algorithm is called immediately.
Problem: It may be, that the drawing process isn't finished and in the walls/obstacles/startPos/goalPos aren't up to date.
Implement functionality, that checks if everything is finished before calling endpoint.

**Comment by florianlan** [comment]
![Image](https://user-images.githubusercontent.com/56444998/211937799-1b3ace75-499f-4198-9cb1-e26fed2d7fec.png)

The new path isn't generated, because the new startPosition is not recognized.

**Comment by fragjulian** [comment]
an easier solution for this problem would be to just wait a few ms before calling the endpoint

**Comment by gregorla12** [comment]
I will take a look at this. Maybe we should continiue with merging our branch and fix this bug later to avoid further delaing the merge.
